// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 3166-1.proto

/*
Package country is a generated protocol buffer package.

It is generated from these files:
	3166-1.proto

It has these top-level messages:
*/
package country

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CountryCode int32

const (
	CountryCode__ CountryCode = 0
	// *
	//
	CountryCode_TWN CountryCode = 158
	// *
	//
	CountryCode_AFG CountryCode = 4
	// *
	//
	CountryCode_ALB CountryCode = 8
	// *
	//
	CountryCode_DZA CountryCode = 12
	// *
	//
	CountryCode_ASM CountryCode = 16
	// *
	//
	CountryCode_AND CountryCode = 20
	// *
	//
	CountryCode_AGO CountryCode = 24
	// *
	//
	CountryCode_AIA CountryCode = 660
	// *
	//
	CountryCode_ATA CountryCode = 10
	// *
	//
	CountryCode_ATG CountryCode = 28
	// *
	//
	CountryCode_ARG CountryCode = 32
	// *
	//
	CountryCode_ARM CountryCode = 51
	// *
	//
	CountryCode_ABW CountryCode = 533
	// *
	//
	CountryCode_AUS CountryCode = 36
	// *
	//
	CountryCode_AUT CountryCode = 40
	// *
	//
	CountryCode_AZE CountryCode = 31
	// *
	//
	CountryCode_BHS CountryCode = 44
	// *
	//
	CountryCode_BHR CountryCode = 48
	// *
	//
	CountryCode_BGD CountryCode = 50
	// *
	//
	CountryCode_BRB CountryCode = 52
	// *
	//
	CountryCode_BLR CountryCode = 112
	// *
	//
	CountryCode_BEL CountryCode = 56
	// *
	//
	CountryCode_BLZ CountryCode = 84
	// *
	//
	CountryCode_BEN CountryCode = 204
	// *
	//
	CountryCode_BMU CountryCode = 60
	// *
	//
	CountryCode_BTN CountryCode = 64
	// *
	//
	CountryCode_BOL CountryCode = 68
	// *
	//
	CountryCode_BES CountryCode = 535
	// *
	//
	CountryCode_BIH CountryCode = 70
	// *
	//
	CountryCode_BWA CountryCode = 72
	// *
	//
	CountryCode_BVT CountryCode = 74
	// *
	//
	CountryCode_BRA CountryCode = 76
	// *
	//
	CountryCode_IOT CountryCode = 86
	// *
	//
	CountryCode_VGB CountryCode = 92
	// *
	//
	CountryCode_BRN CountryCode = 96
	// *
	//
	CountryCode_BGR CountryCode = 100
	// *
	//
	CountryCode_BFA CountryCode = 854
	// *
	//
	CountryCode_BDI CountryCode = 108
	// *
	//
	CountryCode_CPV CountryCode = 132
	// *
	//
	CountryCode_KHM CountryCode = 116
	// *
	//
	CountryCode_CMR CountryCode = 120
	// *
	//
	CountryCode_CAN CountryCode = 124
	// *
	//
	CountryCode_CYM CountryCode = 136
	// *
	//
	CountryCode_CAF CountryCode = 140
	// *
	//
	CountryCode_TCD CountryCode = 148
	// *
	//
	CountryCode_CHL CountryCode = 152
	// *
	//
	CountryCode_CHN CountryCode = 156
	// *
	//
	CountryCode_HKG CountryCode = 344
	// *
	//
	CountryCode_MAC CountryCode = 446
	// *
	//
	CountryCode_CXR CountryCode = 162
	// *
	//
	CountryCode_CCK CountryCode = 166
	// *
	//
	CountryCode_COL CountryCode = 170
	// *
	//
	CountryCode_COM CountryCode = 174
	// *
	//
	CountryCode_COG CountryCode = 178
	// *
	//
	CountryCode_COK CountryCode = 184
	// *
	//
	CountryCode_CRI CountryCode = 188
	// *
	//
	CountryCode_HRV CountryCode = 191
	// *
	//
	CountryCode_CUB CountryCode = 192
	// *
	//
	CountryCode_CUW CountryCode = 531
	// *
	//
	CountryCode_CYP CountryCode = 196
	// *
	//
	CountryCode_CZE CountryCode = 203
	// *
	//
	CountryCode_CIV CountryCode = 384
	// *
	//
	CountryCode_PRK CountryCode = 408
	// *
	//
	CountryCode_COD CountryCode = 180
	// *
	//
	CountryCode_DNK CountryCode = 208
	// *
	//
	CountryCode_DJI CountryCode = 262
	// *
	//
	CountryCode_DMA CountryCode = 212
	// *
	//
	CountryCode_DOM CountryCode = 214
	// *
	//
	CountryCode_ECU CountryCode = 218
	// *
	//
	CountryCode_EGY CountryCode = 818
	// *
	//
	CountryCode_SLV CountryCode = 222
	// *
	//
	CountryCode_GNQ CountryCode = 226
	// *
	//
	CountryCode_ERI CountryCode = 232
	// *
	//
	CountryCode_EST CountryCode = 233
	// *
	//
	CountryCode_ETH CountryCode = 231
	// *
	//
	CountryCode_FLK CountryCode = 238
	// *
	//
	CountryCode_FRO CountryCode = 234
	// *
	//
	CountryCode_FJI CountryCode = 242
	// *
	//
	CountryCode_FIN CountryCode = 246
	// *
	//
	CountryCode_FRA CountryCode = 250
	// *
	//
	CountryCode_GUF CountryCode = 254
	// *
	//
	CountryCode_PYF CountryCode = 258
	// *
	//
	CountryCode_ATF CountryCode = 260
	// *
	//
	CountryCode_GAB CountryCode = 266
	// *
	//
	CountryCode_GMB CountryCode = 270
	// *
	//
	CountryCode_GEO CountryCode = 268
	// *
	//
	CountryCode_DEU CountryCode = 276
	// *
	//
	CountryCode_GHA CountryCode = 288
	// *
	//
	CountryCode_GIB CountryCode = 292
	// *
	//
	CountryCode_GRC CountryCode = 300
	// *
	//
	CountryCode_GRL CountryCode = 304
	// *
	//
	CountryCode_GRD CountryCode = 308
	// *
	//
	CountryCode_GLP CountryCode = 312
	// *
	//
	CountryCode_GUM CountryCode = 316
	// *
	//
	CountryCode_GTM CountryCode = 320
	// *
	//
	CountryCode_GGY CountryCode = 831
	// *
	//
	CountryCode_GIN CountryCode = 324
	// *
	//
	CountryCode_GNB CountryCode = 624
	// *
	//
	CountryCode_GUY CountryCode = 328
	// *
	//
	CountryCode_HTI CountryCode = 332
	// *
	//
	CountryCode_HMD CountryCode = 334
	// *
	//
	CountryCode_VAT CountryCode = 336
	// *
	//
	CountryCode_HND CountryCode = 340
	// *
	//
	CountryCode_HUN CountryCode = 348
	// *
	//
	CountryCode_ISL CountryCode = 352
	// *
	//
	CountryCode_IND CountryCode = 356
	// *
	//
	CountryCode_IDN CountryCode = 360
	// *
	//
	CountryCode_IRN CountryCode = 364
	// *
	//
	CountryCode_IRQ CountryCode = 368
	// *
	//
	CountryCode_IRL CountryCode = 372
	// *
	//
	CountryCode_IMN CountryCode = 833
	// *
	//
	CountryCode_ISR CountryCode = 376
	// *
	//
	CountryCode_ITA CountryCode = 380
	// *
	//
	CountryCode_JAM CountryCode = 388
	// *
	//
	CountryCode_JPN CountryCode = 392
	// *
	//
	CountryCode_JEY CountryCode = 832
	// *
	//
	CountryCode_JOR CountryCode = 400
	// *
	//
	CountryCode_KAZ CountryCode = 398
	// *
	//
	CountryCode_KEN CountryCode = 404
	// *
	//
	CountryCode_KIR CountryCode = 296
	// *
	//
	CountryCode_KWT CountryCode = 414
	// *
	//
	CountryCode_KGZ CountryCode = 417
	// *
	//
	CountryCode_LAO CountryCode = 418
	// *
	//
	CountryCode_LVA CountryCode = 428
	// *
	//
	CountryCode_LBN CountryCode = 422
	// *
	//
	CountryCode_LSO CountryCode = 426
	// *
	//
	CountryCode_LBR CountryCode = 430
	// *
	//
	CountryCode_LBY CountryCode = 434
	// *
	//
	CountryCode_LIE CountryCode = 438
	// *
	//
	CountryCode_LTU CountryCode = 440
	// *
	//
	CountryCode_LUX CountryCode = 442
	// *
	//
	CountryCode_MDG CountryCode = 450
	// *
	//
	CountryCode_MWI CountryCode = 454
	// *
	//
	CountryCode_MYS CountryCode = 458
	// *
	//
	CountryCode_MDV CountryCode = 462
	// *
	//
	CountryCode_MLI CountryCode = 466
	// *
	//
	CountryCode_MLT CountryCode = 470
	// *
	//
	CountryCode_MHL CountryCode = 584
	// *
	//
	CountryCode_MTQ CountryCode = 474
	// *
	//
	CountryCode_MRT CountryCode = 478
	// *
	//
	CountryCode_MUS CountryCode = 480
	// *
	//
	CountryCode_MYT CountryCode = 175
	// *
	//
	CountryCode_MEX CountryCode = 484
	// *
	//
	CountryCode_FSM CountryCode = 583
	// *
	//
	CountryCode_MCO CountryCode = 492
	// *
	//
	CountryCode_MNG CountryCode = 496
	// *
	//
	CountryCode_MNE CountryCode = 499
	// *
	//
	CountryCode_MSR CountryCode = 500
	// *
	//
	CountryCode_MAR CountryCode = 504
	// *
	//
	CountryCode_MOZ CountryCode = 508
	// *
	//
	CountryCode_MMR CountryCode = 104
	// *
	//
	CountryCode_NAM CountryCode = 516
	// *
	//
	CountryCode_NRU CountryCode = 520
	// *
	//
	CountryCode_NPL CountryCode = 524
	// *
	//
	CountryCode_NLD CountryCode = 528
	// *
	//
	CountryCode_NCL CountryCode = 540
	// *
	//
	CountryCode_NZL CountryCode = 554
	// *
	//
	CountryCode_NIC CountryCode = 558
	// *
	//
	CountryCode_NER CountryCode = 562
	// *
	//
	CountryCode_NGA CountryCode = 566
	// *
	//
	CountryCode_NIU CountryCode = 570
	// *
	//
	CountryCode_NFK CountryCode = 574
	// *
	//
	CountryCode_MNP CountryCode = 580
	// *
	//
	CountryCode_NOR CountryCode = 578
	// *
	//
	CountryCode_OMN CountryCode = 512
	// *
	//
	CountryCode_PAK CountryCode = 586
	// *
	//
	CountryCode_PLW CountryCode = 585
	// *
	//
	CountryCode_PAN CountryCode = 591
	// *
	//
	CountryCode_PNG CountryCode = 598
	// *
	//
	CountryCode_PRY CountryCode = 600
	// *
	//
	CountryCode_PER CountryCode = 604
	// *
	//
	CountryCode_PHL CountryCode = 608
	// *
	//
	CountryCode_PCN CountryCode = 612
	// *
	//
	CountryCode_POL CountryCode = 616
	// *
	//
	CountryCode_PRT CountryCode = 620
	// *
	//
	CountryCode_PRI CountryCode = 630
	// *
	//
	CountryCode_QAT CountryCode = 634
	// *
	//
	CountryCode_KOR CountryCode = 410
	// *
	//
	CountryCode_MDA CountryCode = 498
	// *
	//
	CountryCode_ROU CountryCode = 642
	// *
	//
	CountryCode_RUS CountryCode = 643
	// *
	//
	CountryCode_RWA CountryCode = 646
	// *
	//
	CountryCode_REU CountryCode = 638
	// *
	//
	CountryCode_BLM CountryCode = 652
	// *
	//
	CountryCode_SHN CountryCode = 654
	// *
	//
	CountryCode_KNA CountryCode = 659
	// *
	//
	CountryCode_LCA CountryCode = 662
	// *
	//
	CountryCode_MAF CountryCode = 663
	// *
	//
	CountryCode_SPM CountryCode = 666
	// *
	//
	CountryCode_VCT CountryCode = 670
	// *
	//
	CountryCode_WSM CountryCode = 882
	// *
	//
	CountryCode_SMR CountryCode = 674
	// *
	//
	CountryCode_STP CountryCode = 678
	// *
	//
	CountryCode_SAU CountryCode = 682
	// *
	//
	CountryCode_SEN CountryCode = 686
	// *
	//
	CountryCode_SRB CountryCode = 688
	// *
	//
	CountryCode_SYC CountryCode = 690
	// *
	//
	CountryCode_SLE CountryCode = 694
	// *
	//
	CountryCode_SGP CountryCode = 702
	// *
	//
	CountryCode_SXM CountryCode = 534
	// *
	//
	CountryCode_SVK CountryCode = 703
	// *
	//
	CountryCode_SVN CountryCode = 705
	// *
	//
	CountryCode_SLB CountryCode = 90
	// *
	//
	CountryCode_SOM CountryCode = 706
	// *
	//
	CountryCode_ZAF CountryCode = 710
	// *
	//
	CountryCode_SGS CountryCode = 239
	// *
	//
	CountryCode_SSD CountryCode = 728
	// *
	//
	CountryCode_ESP CountryCode = 724
	// *
	//
	CountryCode_LKA CountryCode = 144
	// *
	//
	CountryCode_PSE CountryCode = 275
	// *
	//
	CountryCode_SDN CountryCode = 729
	// *
	//
	CountryCode_SUR CountryCode = 740
	// *
	//
	CountryCode_SJM CountryCode = 744
	// *
	//
	CountryCode_SWZ CountryCode = 748
	// *
	//
	CountryCode_SWE CountryCode = 752
	// *
	//
	CountryCode_CHE CountryCode = 756
	// *
	//
	CountryCode_SYR CountryCode = 760
	// *
	//
	CountryCode_TJK CountryCode = 762
	// *
	//
	CountryCode_THA CountryCode = 764
	// *
	//
	CountryCode_MKD CountryCode = 807
	// *
	//
	CountryCode_TLS CountryCode = 626
	// *
	//
	CountryCode_TGO CountryCode = 768
	// *
	//
	CountryCode_TKL CountryCode = 772
	// *
	//
	CountryCode_TON CountryCode = 776
	// *
	//
	CountryCode_TTO CountryCode = 780
	// *
	//
	CountryCode_TUN CountryCode = 788
	// *
	//
	CountryCode_TUR CountryCode = 792
	// *
	//
	CountryCode_TKM CountryCode = 795
	// *
	//
	CountryCode_TCA CountryCode = 796
	// *
	//
	CountryCode_TUV CountryCode = 798
	// *
	//
	CountryCode_UGA CountryCode = 800
	// *
	//
	CountryCode_UKR CountryCode = 804
	// *
	//
	CountryCode_ARE CountryCode = 784
	// *
	//
	CountryCode_GBR CountryCode = 826
	// *
	//
	CountryCode_TZA CountryCode = 834
	// *
	//
	CountryCode_UMI CountryCode = 581
	// *
	//
	CountryCode_VIR CountryCode = 850
	// *
	//
	CountryCode_USA CountryCode = 840
	// *
	//
	CountryCode_URY CountryCode = 858
	// *
	//
	CountryCode_UZB CountryCode = 860
	// *
	//
	CountryCode_VUT CountryCode = 548
	// *
	//
	CountryCode_VEN CountryCode = 862
	// *
	//
	CountryCode_VNM CountryCode = 704
	// *
	//
	CountryCode_WLF CountryCode = 876
	// *
	//
	CountryCode_ESH CountryCode = 732
	// *
	//
	CountryCode_YEM CountryCode = 887
	// *
	//
	CountryCode_ZMB CountryCode = 894
	// *
	//
	CountryCode_ZWE CountryCode = 716
	// *
	//
	CountryCode_ALA CountryCode = 248
)

var CountryCode_name = map[int32]string{
	0:   "_",
	158: "TWN",
	4:   "AFG",
	8:   "ALB",
	12:  "DZA",
	16:  "ASM",
	20:  "AND",
	24:  "AGO",
	660: "AIA",
	10:  "ATA",
	28:  "ATG",
	32:  "ARG",
	51:  "ARM",
	533: "ABW",
	36:  "AUS",
	40:  "AUT",
	31:  "AZE",
	44:  "BHS",
	48:  "BHR",
	50:  "BGD",
	52:  "BRB",
	112: "BLR",
	56:  "BEL",
	84:  "BLZ",
	204: "BEN",
	60:  "BMU",
	64:  "BTN",
	68:  "BOL",
	535: "BES",
	70:  "BIH",
	72:  "BWA",
	74:  "BVT",
	76:  "BRA",
	86:  "IOT",
	92:  "VGB",
	96:  "BRN",
	100: "BGR",
	854: "BFA",
	108: "BDI",
	132: "CPV",
	116: "KHM",
	120: "CMR",
	124: "CAN",
	136: "CYM",
	140: "CAF",
	148: "TCD",
	152: "CHL",
	156: "CHN",
	344: "HKG",
	446: "MAC",
	162: "CXR",
	166: "CCK",
	170: "COL",
	174: "COM",
	178: "COG",
	184: "COK",
	188: "CRI",
	191: "HRV",
	192: "CUB",
	531: "CUW",
	196: "CYP",
	203: "CZE",
	384: "CIV",
	408: "PRK",
	180: "COD",
	208: "DNK",
	262: "DJI",
	212: "DMA",
	214: "DOM",
	218: "ECU",
	818: "EGY",
	222: "SLV",
	226: "GNQ",
	232: "ERI",
	233: "EST",
	231: "ETH",
	238: "FLK",
	234: "FRO",
	242: "FJI",
	246: "FIN",
	250: "FRA",
	254: "GUF",
	258: "PYF",
	260: "ATF",
	266: "GAB",
	270: "GMB",
	268: "GEO",
	276: "DEU",
	288: "GHA",
	292: "GIB",
	300: "GRC",
	304: "GRL",
	308: "GRD",
	312: "GLP",
	316: "GUM",
	320: "GTM",
	831: "GGY",
	324: "GIN",
	624: "GNB",
	328: "GUY",
	332: "HTI",
	334: "HMD",
	336: "VAT",
	340: "HND",
	348: "HUN",
	352: "ISL",
	356: "IND",
	360: "IDN",
	364: "IRN",
	368: "IRQ",
	372: "IRL",
	833: "IMN",
	376: "ISR",
	380: "ITA",
	388: "JAM",
	392: "JPN",
	832: "JEY",
	400: "JOR",
	398: "KAZ",
	404: "KEN",
	296: "KIR",
	414: "KWT",
	417: "KGZ",
	418: "LAO",
	428: "LVA",
	422: "LBN",
	426: "LSO",
	430: "LBR",
	434: "LBY",
	438: "LIE",
	440: "LTU",
	442: "LUX",
	450: "MDG",
	454: "MWI",
	458: "MYS",
	462: "MDV",
	466: "MLI",
	470: "MLT",
	584: "MHL",
	474: "MTQ",
	478: "MRT",
	480: "MUS",
	175: "MYT",
	484: "MEX",
	583: "FSM",
	492: "MCO",
	496: "MNG",
	499: "MNE",
	500: "MSR",
	504: "MAR",
	508: "MOZ",
	104: "MMR",
	516: "NAM",
	520: "NRU",
	524: "NPL",
	528: "NLD",
	540: "NCL",
	554: "NZL",
	558: "NIC",
	562: "NER",
	566: "NGA",
	570: "NIU",
	574: "NFK",
	580: "MNP",
	578: "NOR",
	512: "OMN",
	586: "PAK",
	585: "PLW",
	591: "PAN",
	598: "PNG",
	600: "PRY",
	604: "PER",
	608: "PHL",
	612: "PCN",
	616: "POL",
	620: "PRT",
	630: "PRI",
	634: "QAT",
	410: "KOR",
	498: "MDA",
	642: "ROU",
	643: "RUS",
	646: "RWA",
	638: "REU",
	652: "BLM",
	654: "SHN",
	659: "KNA",
	662: "LCA",
	663: "MAF",
	666: "SPM",
	670: "VCT",
	882: "WSM",
	674: "SMR",
	678: "STP",
	682: "SAU",
	686: "SEN",
	688: "SRB",
	690: "SYC",
	694: "SLE",
	702: "SGP",
	534: "SXM",
	703: "SVK",
	705: "SVN",
	90:  "SLB",
	706: "SOM",
	710: "ZAF",
	239: "SGS",
	728: "SSD",
	724: "ESP",
	144: "LKA",
	275: "PSE",
	729: "SDN",
	740: "SUR",
	744: "SJM",
	748: "SWZ",
	752: "SWE",
	756: "CHE",
	760: "SYR",
	762: "TJK",
	764: "THA",
	807: "MKD",
	626: "TLS",
	768: "TGO",
	772: "TKL",
	776: "TON",
	780: "TTO",
	788: "TUN",
	792: "TUR",
	795: "TKM",
	796: "TCA",
	798: "TUV",
	800: "UGA",
	804: "UKR",
	784: "ARE",
	826: "GBR",
	834: "TZA",
	581: "UMI",
	850: "VIR",
	840: "USA",
	858: "URY",
	860: "UZB",
	548: "VUT",
	862: "VEN",
	704: "VNM",
	876: "WLF",
	732: "ESH",
	887: "YEM",
	894: "ZMB",
	716: "ZWE",
	248: "ALA",
}
var CountryCode_value = map[string]int32{
	"_":   0,
	"TWN": 158,
	"AFG": 4,
	"ALB": 8,
	"DZA": 12,
	"ASM": 16,
	"AND": 20,
	"AGO": 24,
	"AIA": 660,
	"ATA": 10,
	"ATG": 28,
	"ARG": 32,
	"ARM": 51,
	"ABW": 533,
	"AUS": 36,
	"AUT": 40,
	"AZE": 31,
	"BHS": 44,
	"BHR": 48,
	"BGD": 50,
	"BRB": 52,
	"BLR": 112,
	"BEL": 56,
	"BLZ": 84,
	"BEN": 204,
	"BMU": 60,
	"BTN": 64,
	"BOL": 68,
	"BES": 535,
	"BIH": 70,
	"BWA": 72,
	"BVT": 74,
	"BRA": 76,
	"IOT": 86,
	"VGB": 92,
	"BRN": 96,
	"BGR": 100,
	"BFA": 854,
	"BDI": 108,
	"CPV": 132,
	"KHM": 116,
	"CMR": 120,
	"CAN": 124,
	"CYM": 136,
	"CAF": 140,
	"TCD": 148,
	"CHL": 152,
	"CHN": 156,
	"HKG": 344,
	"MAC": 446,
	"CXR": 162,
	"CCK": 166,
	"COL": 170,
	"COM": 174,
	"COG": 178,
	"COK": 184,
	"CRI": 188,
	"HRV": 191,
	"CUB": 192,
	"CUW": 531,
	"CYP": 196,
	"CZE": 203,
	"CIV": 384,
	"PRK": 408,
	"COD": 180,
	"DNK": 208,
	"DJI": 262,
	"DMA": 212,
	"DOM": 214,
	"ECU": 218,
	"EGY": 818,
	"SLV": 222,
	"GNQ": 226,
	"ERI": 232,
	"EST": 233,
	"ETH": 231,
	"FLK": 238,
	"FRO": 234,
	"FJI": 242,
	"FIN": 246,
	"FRA": 250,
	"GUF": 254,
	"PYF": 258,
	"ATF": 260,
	"GAB": 266,
	"GMB": 270,
	"GEO": 268,
	"DEU": 276,
	"GHA": 288,
	"GIB": 292,
	"GRC": 300,
	"GRL": 304,
	"GRD": 308,
	"GLP": 312,
	"GUM": 316,
	"GTM": 320,
	"GGY": 831,
	"GIN": 324,
	"GNB": 624,
	"GUY": 328,
	"HTI": 332,
	"HMD": 334,
	"VAT": 336,
	"HND": 340,
	"HUN": 348,
	"ISL": 352,
	"IND": 356,
	"IDN": 360,
	"IRN": 364,
	"IRQ": 368,
	"IRL": 372,
	"IMN": 833,
	"ISR": 376,
	"ITA": 380,
	"JAM": 388,
	"JPN": 392,
	"JEY": 832,
	"JOR": 400,
	"KAZ": 398,
	"KEN": 404,
	"KIR": 296,
	"KWT": 414,
	"KGZ": 417,
	"LAO": 418,
	"LVA": 428,
	"LBN": 422,
	"LSO": 426,
	"LBR": 430,
	"LBY": 434,
	"LIE": 438,
	"LTU": 440,
	"LUX": 442,
	"MDG": 450,
	"MWI": 454,
	"MYS": 458,
	"MDV": 462,
	"MLI": 466,
	"MLT": 470,
	"MHL": 584,
	"MTQ": 474,
	"MRT": 478,
	"MUS": 480,
	"MYT": 175,
	"MEX": 484,
	"FSM": 583,
	"MCO": 492,
	"MNG": 496,
	"MNE": 499,
	"MSR": 500,
	"MAR": 504,
	"MOZ": 508,
	"MMR": 104,
	"NAM": 516,
	"NRU": 520,
	"NPL": 524,
	"NLD": 528,
	"NCL": 540,
	"NZL": 554,
	"NIC": 558,
	"NER": 562,
	"NGA": 566,
	"NIU": 570,
	"NFK": 574,
	"MNP": 580,
	"NOR": 578,
	"OMN": 512,
	"PAK": 586,
	"PLW": 585,
	"PAN": 591,
	"PNG": 598,
	"PRY": 600,
	"PER": 604,
	"PHL": 608,
	"PCN": 612,
	"POL": 616,
	"PRT": 620,
	"PRI": 630,
	"QAT": 634,
	"KOR": 410,
	"MDA": 498,
	"ROU": 642,
	"RUS": 643,
	"RWA": 646,
	"REU": 638,
	"BLM": 652,
	"SHN": 654,
	"KNA": 659,
	"LCA": 662,
	"MAF": 663,
	"SPM": 666,
	"VCT": 670,
	"WSM": 882,
	"SMR": 674,
	"STP": 678,
	"SAU": 682,
	"SEN": 686,
	"SRB": 688,
	"SYC": 690,
	"SLE": 694,
	"SGP": 702,
	"SXM": 534,
	"SVK": 703,
	"SVN": 705,
	"SLB": 90,
	"SOM": 706,
	"ZAF": 710,
	"SGS": 239,
	"SSD": 728,
	"ESP": 724,
	"LKA": 144,
	"PSE": 275,
	"SDN": 729,
	"SUR": 740,
	"SJM": 744,
	"SWZ": 748,
	"SWE": 752,
	"CHE": 756,
	"SYR": 760,
	"TJK": 762,
	"THA": 764,
	"MKD": 807,
	"TLS": 626,
	"TGO": 768,
	"TKL": 772,
	"TON": 776,
	"TTO": 780,
	"TUN": 788,
	"TUR": 792,
	"TKM": 795,
	"TCA": 796,
	"TUV": 798,
	"UGA": 800,
	"UKR": 804,
	"ARE": 784,
	"GBR": 826,
	"TZA": 834,
	"UMI": 581,
	"VIR": 850,
	"USA": 840,
	"URY": 858,
	"UZB": 860,
	"VUT": 548,
	"VEN": 862,
	"VNM": 704,
	"WLF": 876,
	"ESH": 732,
	"YEM": 887,
	"ZMB": 894,
	"ZWE": 716,
	"ALA": 248,
}

func (x CountryCode) String() string {
	return proto.EnumName(CountryCode_name, int32(x))
}
func (CountryCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("country.CountryCode", CountryCode_name, CountryCode_value)
}

func init() { proto.RegisterFile("3166-1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xd6, 0x4d, 0x68, 0x55, 0xd7,
	0x16, 0x07, 0xf0, 0x97, 0x17, 0x13, 0x25, 0xcf, 0xc1, 0x9f, 0xbc, 0x37, 0x78, 0x83, 0x07, 0xaf,
	0x83, 0x0e, 0x4a, 0x69, 0x4b, 0xad, 0x45, 0x3a, 0xe8, 0xa0, 0xfb, 0x7c, 0xdc, 0x73, 0xcf, 0x3d,
	0x7b, 0xef, 0x73, 0xb3, 0xcf, 0xc7, 0xcd, 0xbd, 0x14, 0x5a, 0x5a, 0x0b, 0x1d, 0x94, 0x46, 0xc4,
	0x42, 0x0b, 0x1d, 0x88, 0x0d, 0x12, 0x4a, 0x90, 0x80, 0xa9, 0x8a, 0x95, 0x60, 0x45, 0x6c, 0x1b,
	0x24, 0x95, 0x20, 0x22, 0x22, 0x1a, 0x83, 0xb5, 0xd6, 0x8a, 0x15, 0x91, 0x60, 0x25, 0x88, 0x94,
	0x40, 0xd3, 0x12, 0xda, 0x90, 0x8a, 0x0d, 0x22, 0x52, 0xee, 0xfa, 0x9f, 0xd9, 0x8f, 0xff, 0xda,
	0x6b, 0x9f, 0x75, 0x3e, 0xb2, 0x6f, 0x06, 0x36, 0x6f, 0xdd, 0xb2, 0x6d, 0xdb, 0xf3, 0x5b, 0x5e,
	0xd8, 0xb1, 0x73, 0x64, 0xd7, 0xc8, 0xe0, 0xc6, 0xb7, 0x47, 0x3e, 0x78, 0x7f, 0xd7, 0xce, 0x8f,
	0x9e, 0xfd, 0xfa, 0xdf, 0x03, 0xff, 0xf2, 0x69, 0x7f, 0x64, 0xfb, 0x3b, 0x83, 0x7d, 0x03, 0x3d,
	0x6f, 0xe0, 0x1f, 0x83, 0x9b, 0x06, 0x7a, 0xf3, 0x96, 0xc5, 0x54, 0xcf, 0xe0, 0xc6, 0x81, 0x5e,
	0x55, 0x8b, 0xb0, 0x41, 0xa0, 0x3d, 0x6c, 0xea, 0x22, 0xe8, 0x28, 0x6c, 0x96, 0x24, 0x33, 0x80,
	0xc0, 0x06, 0xf8, 0x8f, 0x20, 0x4a, 0xf1, 0xdf, 0x6e, 0xbf, 0x8a, 0x15, 0x26, 0xfb, 0x24, 0xca,
	0x15, 0x06, 0x88, 0x08, 0xff, 0x13, 0xb8, 0x08, 0x4f, 0x11, 0x06, 0x5b, 0x65, 0xb5, 0xd7, 0xc2,
	0x67, 0xbc, 0x48, 0x91, 0xe1, 0x69, 0x22, 0xc7, 0x33, 0x82, 0x4e, 0x88, 0xff, 0x77, 0xe1, 0xd5,
	0x33, 0x3c, 0x47, 0x38, 0xbc, 0x28, 0x88, 0x02, 0xbc, 0x24, 0x70, 0x1e, 0x5e, 0x16, 0x68, 0x87,
	0x1d, 0x82, 0x50, 0xe3, 0x15, 0x26, 0x1d, 0xe4, 0xdd, 0x6b, 0x78, 0xa1, 0xc5, 0x75, 0xb9, 0x23,
	0xcf, 0x14, 0x78, 0x55, 0x90, 0x5b, 0xbc, 0x26, 0x48, 0x35, 0x02, 0x2e, 0xca, 0x70, 0x50, 0x06,
	0xf1, 0xe2, 0x3a, 0x6a, 0x82, 0x96, 0x42, 0x5d, 0x50, 0xe6, 0x68, 0xf0, 0x6a, 0x0a, 0xba, 0x8b,
	0x38, 0xcd, 0x51, 0x76, 0x51, 0x46, 0x1e, 0x5e, 0x67, 0xc9, 0xe2, 0x4d, 0x8e, 0xe6, 0xb0, 0x5d,
	0x76, 0xac, 0x29, 0x2c, 0xf4, 0x4b, 0x14, 0xc4, 0x78, 0xaf, 0x1b, 0xf9, 0xcd, 0x12, 0xa3, 0x32,
	0x49, 0x52, 0x37, 0xd8, 0xd5, 0x85, 0x6f, 0x1c, 0x3e, 0x14, 0x28, 0x8b, 0x8f, 0x65, 0x51, 0xdb,
	0x60, 0xac, 0x47, 0xa4, 0x6a, 0x18, 0x17, 0xe5, 0x7e, 0x80, 0x49, 0x66, 0x75, 0x8d, 0x43, 0x95,
	0x2c, 0x8e, 0x88, 0xea, 0x49, 0x84, 0x3b, 0xff, 0xec, 0xca, 0x28, 0x1f, 0x17, 0x7a, 0xa5, 0x3a,
	0xec, 0x70, 0x8c, 0xeb, 0xfc, 0x04, 0x27, 0xa8, 0x54, 0x63, 0xba, 0x92, 0xc1, 0x4c, 0xa5, 0x08,
	0xb3, 0x95, 0x12, 0x9c, 0xa5, 0x5c, 0x8c, 0xf3, 0xdc, 0xd9, 0x95, 0xb8, 0xc8, 0xac, 0xf0, 0x30,
	0x57, 0xa9, 0x85, 0xfd, 0x1b, 0x38, 0x69, 0x13, 0x97, 0x99, 0x75, 0x42, 0xfc, 0x40, 0xc5, 0x25,
	0x76, 0xcb, 0x04, 0x4d, 0x97, 0xe0, 0x10, 0x67, 0x49, 0x03, 0x9c, 0x96, 0x6a, 0x60, 0x13, 0xdc,
	0xa4, 0x1a, 0x31, 0xf6, 0xca, 0xcc, 0x81, 0x51, 0xb8, 0xcd, 0x2c, 0x35, 0x58, 0x10, 0x85, 0x7e,
	0x81, 0xbb, 0x54, 0xd4, 0xc6, 0x6c, 0x7f, 0x57, 0x99, 0x2e, 0x71, 0x4f, 0xb2, 0xc8, 0x0e, 0xe1,
	0x67, 0x56, 0x5d, 0x8c, 0x65, 0x2a, 0xcb, 0xf1, 0x2b, 0x95, 0xd7, 0xf1, 0x8b, 0xa8, 0xa6, 0x13,
	0xfc, 0x4e, 0xb9, 0x14, 0xbf, 0x51, 0x8d, 0x18, 0x6b, 0x54, 0x6c, 0xf1, 0xb0, 0xaa, 0x2a, 0x3c,
	0xe2, 0xce, 0x45, 0x0d, 0x4f, 0x44, 0xcd, 0x76, 0x0d, 0x7b, 0x64, 0x3e, 0x95, 0xd7, 0x30, 0x2a,
	0x8a, 0x94, 0x87, 0x4f, 0x29, 0xe3, 0x61, 0x1f, 0x15, 0xa6, 0x18, 0xe7, 0x7d, 0x84, 0x05, 0x26,
	0x99, 0xd5, 0x15, 0x8e, 0x52, 0xb1, 0x87, 0xe3, 0x94, 0xf3, 0x71, 0xb2, 0x92, 0xc6, 0xa9, 0x4a,
	0x01, 0x4e, 0x53, 0xba, 0x89, 0xb3, 0x54, 0x61, 0x70, 0x9e, 0xca, 0x0d, 0xe6, 0xa8, 0xa8, 0x8d,
	0x8b, 0xfd, 0xdc, 0xcf, 0xe2, 0x32, 0x33, 0xeb, 0x61, 0x75, 0x03, 0x3b, 0xda, 0xb8, 0x2a, 0x59,
	0x3d, 0x8f, 0x71, 0x9d, 0x32, 0x01, 0x6e, 0x88, 0x4a, 0x95, 0xe3, 0x26, 0x33, 0x1b, 0xe0, 0x36,
	0x55, 0x58, 0x2c, 0x8a, 0xe2, 0x4c, 0xe3, 0x3e, 0x65, 0x03, 0x2c, 0x51, 0x81, 0xc5, 0x32, 0xe5,
	0x2c, 0x56, 0x2a, 0x0d, 0x61, 0xb5, 0x92, 0xc6, 0x03, 0xca, 0x58, 0x5c, 0xea, 0xe7, 0x2e, 0x0e,
	0xeb, 0xcc, 0x72, 0x85, 0xc7, 0xa2, 0x86, 0x32, 0x18, 0x95, 0xb7, 0xdf, 0x68, 0x5a, 0x8c, 0x51,
	0x61, 0x1b, 0x73, 0xd2, 0xd1, 0x48, 0x1d, 0x26, 0x24, 0x4b, 0x54, 0x07, 0xfb, 0xa8, 0xd0, 0x62,
	0x92, 0x8a, 0x1d, 0xbe, 0x92, 0x5d, 0x92, 0x56, 0x8e, 0x29, 0x66, 0x51, 0x07, 0x5f, 0x88, 0xb4,
	0x4a, 0x71, 0x8c, 0x2a, 0x15, 0x4e, 0x52, 0x9e, 0xc5, 0x09, 0x2a, 0x4b, 0x31, 0x5d, 0x65, 0x0e,
	0x33, 0x95, 0xda, 0x98, 0xa5, 0xe2, 0x10, 0x67, 0xa8, 0xbc, 0xc0, 0x59, 0xaa, 0x18, 0xc6, 0x39,
	0x91, 0x09, 0x22, 0xcc, 0x53, 0xad, 0x18, 0x57, 0xa8, 0x76, 0x86, 0x6b, 0x55, 0xb5, 0xc4, 0x0d,
	0x4a, 0xc7, 0xb8, 0x55, 0x29, 0xc7, 0x02, 0x55, 0xd7, 0xb8, 0x2a, 0xef, 0xc3, 0xe4, 0x43, 0xb8,
	0xcb, 0xcc, 0xe5, 0xb8, 0x47, 0x15, 0x19, 0xee, 0x57, 0xfb, 0xe5, 0xf8, 0x46, 0xbe, 0x30, 0x13,
	0x0e, 0x63, 0x49, 0xb2, 0x5a, 0x66, 0xf0, 0x1d, 0x7b, 0xfd, 0x14, 0x2b, 0x5c, 0x67, 0x23, 0xac,
	0x56, 0x0a, 0xf1, 0x27, 0x95, 0x39, 0x3c, 0xa0, 0x94, 0xc3, 0x3a, 0x95, 0x76, 0xf0, 0xb8, 0xb7,
	0x7b, 0x80, 0x18, 0xe3, 0xf0, 0x6e, 0x37, 0xb2, 0xdd, 0x47, 0x2f, 0xdb, 0x59, 0x57, 0x60, 0x8c,
	0x6a, 0x6a, 0x8c, 0x53, 0x3a, 0xc0, 0x04, 0xe5, 0x6b, 0x1c, 0xa1, 0x3a, 0x1a, 0xd3, 0x54, 0xec,
	0x63, 0x86, 0x0a, 0x1d, 0x66, 0xa9, 0x48, 0xe1, 0x4c, 0x55, 0x2d, 0x70, 0x8e, 0xaa, 0x25, 0xb8,
	0xc0, 0x91, 0x6d, 0x13, 0x97, 0x99, 0xa5, 0x0e, 0xf3, 0xa2, 0xd4, 0x58, 0xec, 0x16, 0x35, 0x55,
	0x82, 0x6b, 0x94, 0x6e, 0xe1, 0xfb, 0x2a, 0xb3, 0xf8, 0x91, 0xb2, 0x11, 0x16, 0x28, 0xd7, 0xc6,
	0x1d, 0x2a, 0x74, 0x58, 0xa4, 0xea, 0x1a, 0xf7, 0x29, 0xdf, 0x62, 0x89, 0x4a, 0x35, 0x96, 0xab,
	0x8e, 0x1c, 0x2b, 0x95, 0x62, 0x3c, 0x14, 0x0d, 0xa9, 0x1c, 0x8f, 0x44, 0x49, 0xea, 0x70, 0xb8,
	0x7a, 0x6d, 0x0a, 0x6b, 0x22, 0x97, 0x16, 0xd8, 0xd3, 0x27, 0x2a, 0x32, 0x7c, 0x42, 0xb5, 0x14,
	0xf6, 0x52, 0x61, 0x81, 0x27, 0xd2, 0xeb, 0x69, 0x83, 0x71, 0xc9, 0xb2, 0xba, 0xc5, 0x3e, 0x51,
	0x62, 0x15, 0xf6, 0x8b, 0xb4, 0xaf, 0x70, 0xa0, 0x8f, 0x2f, 0xa1, 0x86, 0x83, 0x5c, 0xd7, 0x34,
	0x38, 0x2c, 0x2a, 0xfd, 0x1c, 0x53, 0xa2, 0x56, 0x66, 0xb0, 0xc6, 0x83, 0xcb, 0x38, 0x1c, 0xe3,
	0xba, 0xbc, 0x89, 0x13, 0x94, 0x2a, 0x30, 0x4d, 0x85, 0x16, 0x33, 0x94, 0xf3, 0x70, 0x8a, 0x6a,
	0xfb, 0x98, 0xa5, 0x74, 0x88, 0x33, 0x54, 0xd4, 0xc4, 0x05, 0x6a, 0xd8, 0xe0, 0x80, 0x4c, 0x9a,
	0x95, 0x09, 0x2e, 0x32, 0x2b, 0x2d, 0x2e, 0xc9, 0xaf, 0x6e, 0xa6, 0x3d, 0x74, 0x24, 0x4a, 0x0d,
	0xe6, 0xa5, 0xd8, 0x51, 0x35, 0x5c, 0xa9, 0x36, 0xc9, 0xf0, 0x87, 0x7c, 0x7d, 0x59, 0x16, 0xe0,
	0x4e, 0x1f, 0x4f, 0xce, 0x26, 0x6e, 0xf3, 0xd6, 0x12, 0x85, 0x09, 0x9e, 0x7e, 0x59, 0x88, 0xfd,
	0xf2, 0x17, 0x98, 0x05, 0x16, 0x3f, 0xb1, 0xb7, 0x70, 0x58, 0xa2, 0x1a, 0x06, 0xcb, 0x54, 0xab,
	0x83, 0x95, 0x4a, 0x21, 0x56, 0xfb, 0xf8, 0xbb, 0x14, 0xe2, 0x41, 0x75, 0x1b, 0x0e, 0xeb, 0xa2,
	0xbc, 0x91, 0xe0, 0x11, 0x55, 0x57, 0x78, 0xcc, 0xc7, 0x97, 0x04, 0xf8, 0x52, 0x1e, 0x50, 0xae,
	0x33, 0xac, 0xc9, 0x0d, 0xe5, 0x51, 0x8a, 0xdd, 0xcc, 0x12, 0x8d, 0x51, 0x2a, 0xb5, 0x18, 0xa3,
	0xf2, 0x14, 0xe3, 0x54, 0x61, 0x31, 0x59, 0xc9, 0xe1, 0x50, 0xd5, 0x61, 0xf0, 0x39, 0xe5, 0x2b,
	0x1c, 0xa9, 0xaa, 0x25, 0xa6, 0x44, 0x45, 0xa4, 0x70, 0x94, 0x4a, 0x1c, 0x8e, 0x8b, 0x94, 0x0b,
	0x31, 0xc1, 0x73, 0xd5, 0x73, 0x38, 0xc7, 0x8e, 0x8e, 0xc2, 0x3c, 0xd7, 0x99, 0x18, 0xdf, 0xca,
	0x54, 0x65, 0xec, 0x70, 0x8b, 0x59, 0xa6, 0x70, 0x95, 0x72, 0x6d, 0xdc, 0xa5, 0x3a, 0x1e, 0x16,
	0x45, 0x65, 0x91, 0xe3, 0x38, 0x3b, 0x42, 0x8b, 0x7b, 0xcc, 0xac, 0xc1, 0x1c, 0x3f, 0x08, 0x5d,
	0xc3, 0x4a, 0x3f, 0x9f, 0x78, 0x1d, 0x8b, 0x92, 0xb5, 0x43, 0x83, 0xbf, 0x24, 0xeb, 0x18, 0x0f,
	0x4f, 0xa8, 0x56, 0x88, 0xeb, 0x52, 0x55, 0x5a, 0x61, 0xbd, 0xe7, 0xad, 0x7e, 0xf9, 0xdf, 0x6d,
	0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x15, 0x92, 0x5f, 0x8f, 0xcb, 0x09, 0x00, 0x00,
}
