// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 4217.proto

/*
Package currency is a generated protocol buffer package.

It is generated from these files:
	4217.proto

It has these top-level messages:
*/
package currency

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CurrencyCode int32

const (
	CurrencyCode__ CurrencyCode = 0
	// *
	// UAE Dirham
	//
	// * UNITED ARAB EMIRATES (THE)
	//
	CurrencyCode_AED CurrencyCode = 784
	// *
	// Afghani
	//
	// * AFGHANISTAN
	//
	CurrencyCode_AFN CurrencyCode = 971
	// *
	// Lek
	//
	// * ALBANIA
	//
	CurrencyCode_ALL CurrencyCode = 8
	// *
	// Armenian Dram
	//
	// * ARMENIA
	//
	CurrencyCode_AMD CurrencyCode = 51
	// *
	// Netherlands Antillean Guilder
	//
	// * CURAÇAO
	// * SINT MAARTEN (DUTCH PART)
	//
	CurrencyCode_ANG CurrencyCode = 532
	// *
	// Kwanza
	//
	// * ANGOLA
	//
	CurrencyCode_AOA CurrencyCode = 973
	// *
	// Argentine Peso
	//
	// * ARGENTINA
	//
	CurrencyCode_ARS CurrencyCode = 32
	// *
	// Australian Dollar
	//
	// * AUSTRALIA
	// * CHRISTMAS ISLAND
	// * COCOS (KEELING) ISLANDS (THE)
	// * HEARD ISLAND AND McDONALD ISLANDS
	// * KIRIBATI
	// * NAURU
	// * NORFOLK ISLAND
	// * TUVALU
	//
	CurrencyCode_AUD CurrencyCode = 36
	// *
	// Aruban Florin
	//
	// * ARUBA
	//
	CurrencyCode_AWG CurrencyCode = 533
	// *
	// Azerbaijan Manat
	//
	// * AZERBAIJAN
	//
	CurrencyCode_AZN CurrencyCode = 944
	// *
	// Convertible Mark
	//
	// * BOSNIA AND HERZEGOVINA
	//
	CurrencyCode_BAM CurrencyCode = 977
	// *
	// Barbados Dollar
	//
	// * BARBADOS
	//
	CurrencyCode_BBD CurrencyCode = 52
	// *
	// Taka
	//
	// * BANGLADESH
	//
	CurrencyCode_BDT CurrencyCode = 50
	// *
	// Bulgarian Lev
	//
	// * BULGARIA
	//
	CurrencyCode_BGN CurrencyCode = 975
	// *
	// Bahraini Dinar
	//
	// * BAHRAIN
	//
	CurrencyCode_BHD CurrencyCode = 48
	// *
	// Burundi Franc
	//
	// * BURUNDI
	//
	CurrencyCode_BIF CurrencyCode = 108
	// *
	// Bermudian Dollar
	//
	// * BERMUDA
	//
	CurrencyCode_BMD CurrencyCode = 60
	// *
	// Brunei Dollar
	//
	// * BRUNEI DARUSSALAM
	//
	CurrencyCode_BND CurrencyCode = 96
	// *
	// Boliviano
	//
	// * BOLIVIA (PLURINATIONAL STATE OF)
	//
	CurrencyCode_BOB CurrencyCode = 68
	// *
	// Mvdol
	//
	// * BOLIVIA (PLURINATIONAL STATE OF)
	//
	CurrencyCode_BOV CurrencyCode = 984
	// *
	// Brazilian Real
	//
	// * BRAZIL
	//
	CurrencyCode_BRL CurrencyCode = 986
	// *
	// Bahamian Dollar
	//
	// * BAHAMAS (THE)
	//
	CurrencyCode_BSD CurrencyCode = 44
	// *
	// Ngultrum
	//
	// * BHUTAN
	//
	CurrencyCode_BTN CurrencyCode = 64
	// *
	// Pula
	//
	// * BOTSWANA
	//
	CurrencyCode_BWP CurrencyCode = 72
	// *
	// Belarusian Ruble
	//
	// * BELARUS
	//
	CurrencyCode_BYN CurrencyCode = 933
	// *
	// Belize Dollar
	//
	// * BELIZE
	//
	CurrencyCode_BZD CurrencyCode = 84
	// *
	// Canadian Dollar
	//
	// * CANADA
	//
	CurrencyCode_CAD CurrencyCode = 124
	// *
	// Congolese Franc
	//
	// * CONGO (THE DEMOCRATIC REPUBLIC OF THE)
	//
	CurrencyCode_CDF CurrencyCode = 976
	// *
	// WIR Euro
	//
	// * SWITZERLAND
	//
	CurrencyCode_CHE CurrencyCode = 947
	// *
	// Swiss Franc
	//
	// * LIECHTENSTEIN
	// * SWITZERLAND
	//
	CurrencyCode_CHF CurrencyCode = 756
	// *
	// WIR Franc
	//
	// * SWITZERLAND
	//
	CurrencyCode_CHW CurrencyCode = 948
	// *
	// Unidad de Fomento
	//
	// * CHILE
	//
	CurrencyCode_CLF CurrencyCode = 990
	// *
	// Chilean Peso
	//
	// * CHILE
	//
	CurrencyCode_CLP CurrencyCode = 152
	// *
	// Yuan Renminbi
	//
	// * CHINA
	//
	CurrencyCode_CNY CurrencyCode = 156
	// *
	// Colombian Peso
	//
	// * COLOMBIA
	//
	CurrencyCode_COP CurrencyCode = 170
	// *
	// Unidad de Valor Real
	//
	// * COLOMBIA
	//
	CurrencyCode_COU CurrencyCode = 970
	// *
	// Costa Rican Colon
	//
	// * COSTA RICA
	//
	CurrencyCode_CRC CurrencyCode = 188
	// *
	// Peso Convertible
	//
	// * CUBA
	//
	CurrencyCode_CUC CurrencyCode = 931
	// *
	// Cuban Peso
	//
	// * CUBA
	//
	CurrencyCode_CUP CurrencyCode = 192
	// *
	// Cabo Verde Escudo
	//
	// * CABO VERDE
	//
	CurrencyCode_CVE CurrencyCode = 132
	// *
	// Czech Koruna
	//
	// * CZECHIA
	//
	CurrencyCode_CZK CurrencyCode = 203
	// *
	// Djibouti Franc
	//
	// * DJIBOUTI
	//
	CurrencyCode_DJF CurrencyCode = 262
	// *
	// Danish Krone
	//
	// * DENMARK
	// * FAROE ISLANDS (THE)
	// * GREENLAND
	//
	CurrencyCode_DKK CurrencyCode = 208
	// *
	// Dominican Peso
	//
	// * DOMINICAN REPUBLIC (THE)
	//
	CurrencyCode_DOP CurrencyCode = 214
	// *
	// Algerian Dinar
	//
	// * ALGERIA
	//
	CurrencyCode_DZD CurrencyCode = 12
	// *
	// Egyptian Pound
	//
	// * EGYPT
	//
	CurrencyCode_EGP CurrencyCode = 818
	// *
	// Nakfa
	//
	// * ERITREA
	//
	CurrencyCode_ERN CurrencyCode = 232
	// *
	// Ethiopian Birr
	//
	// * ETHIOPIA
	//
	CurrencyCode_ETB CurrencyCode = 230
	// *
	// Euro
	//
	// * ÅLAND ISLANDS
	// * ANDORRA
	// * AUSTRIA
	// * BELGIUM
	// * CYPRUS
	// * ESTONIA
	// * EUROPEAN UNION
	// * FINLAND
	// * FRANCE
	// * FRENCH GUIANA
	// * FRENCH SOUTHERN TERRITORIES (THE)
	// * GERMANY
	// * GREECE
	// * GUADELOUPE
	// * HOLY SEE (THE)
	// * IRELAND
	// * ITALY
	// * LATVIA
	// * LITHUANIA
	// * LUXEMBOURG
	// * MALTA
	// * MARTINIQUE
	// * MAYOTTE
	// * MONACO
	// * MONTENEGRO
	// * NETHERLANDS (THE)
	// * PORTUGAL
	// * RÉUNION
	// * SAINT BARTHÉLEMY
	// * SAINT MARTIN (FRENCH PART)
	// * SAINT PIERRE AND MIQUELON
	// * SAN MARINO
	// * SLOVAKIA
	// * SLOVENIA
	// * SPAIN
	//
	CurrencyCode_EUR CurrencyCode = 978
	// *
	// Fiji Dollar
	//
	// * FIJI
	//
	CurrencyCode_FJD CurrencyCode = 242
	// *
	// Falkland Islands Pound
	//
	// * FALKLAND ISLANDS (THE) [MALVINAS]
	//
	CurrencyCode_FKP CurrencyCode = 238
	// *
	// Pound Sterling
	//
	// * GUERNSEY
	// * ISLE OF MAN
	// * JERSEY
	// * UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)
	//
	CurrencyCode_GBP CurrencyCode = 826
	// *
	// Lari
	//
	// * GEORGIA
	//
	CurrencyCode_GEL CurrencyCode = 981
	// *
	// Ghana Cedi
	//
	// * GHANA
	//
	CurrencyCode_GHS CurrencyCode = 936
	// *
	// Gibraltar Pound
	//
	// * GIBRALTAR
	//
	CurrencyCode_GIP CurrencyCode = 292
	// *
	// Dalasi
	//
	// * GAMBIA (THE)
	//
	CurrencyCode_GMD CurrencyCode = 270
	// *
	// Guinean Franc
	//
	// * GUINEA
	//
	CurrencyCode_GNF CurrencyCode = 324
	// *
	// Quetzal
	//
	// * GUATEMALA
	//
	CurrencyCode_GTQ CurrencyCode = 320
	// *
	// Guyana Dollar
	//
	// * GUYANA
	//
	CurrencyCode_GYD CurrencyCode = 328
	// *
	// Hong Kong Dollar
	//
	// * HONG KONG
	//
	CurrencyCode_HKD CurrencyCode = 344
	// *
	// Lempira
	//
	// * HONDURAS
	//
	CurrencyCode_HNL CurrencyCode = 340
	// *
	// Kuna
	//
	// * CROATIA
	//
	CurrencyCode_HRK CurrencyCode = 191
	// *
	// Gourde
	//
	// * HAITI
	//
	CurrencyCode_HTG CurrencyCode = 332
	// *
	// Forint
	//
	// * HUNGARY
	//
	CurrencyCode_HUF CurrencyCode = 348
	// *
	// Rupiah
	//
	// * INDONESIA
	//
	CurrencyCode_IDR CurrencyCode = 360
	// *
	// New Israeli Sheqel
	//
	// * ISRAEL
	//
	CurrencyCode_ILS CurrencyCode = 376
	// *
	// Indian Rupee
	//
	// * BHUTAN
	// * INDIA
	//
	CurrencyCode_INR CurrencyCode = 356
	// *
	// Iraqi Dinar
	//
	// * IRAQ
	//
	CurrencyCode_IQD CurrencyCode = 368
	// *
	// Iranian Rial
	//
	// * IRAN (ISLAMIC REPUBLIC OF)
	//
	CurrencyCode_IRR CurrencyCode = 364
	// *
	// Iceland Krona
	//
	// * ICELAND
	//
	CurrencyCode_ISK CurrencyCode = 352
	// *
	// Jamaican Dollar
	//
	// * JAMAICA
	//
	CurrencyCode_JMD CurrencyCode = 388
	// *
	// Jordanian Dinar
	//
	// * JORDAN
	//
	CurrencyCode_JOD CurrencyCode = 400
	// *
	// Yen
	//
	// * JAPAN
	//
	CurrencyCode_JPY CurrencyCode = 392
	// *
	// Kenyan Shilling
	//
	// * KENYA
	//
	CurrencyCode_KES CurrencyCode = 404
	// *
	// Som
	//
	// * KYRGYZSTAN
	//
	CurrencyCode_KGS CurrencyCode = 417
	// *
	// Riel
	//
	// * CAMBODIA
	//
	CurrencyCode_KHR CurrencyCode = 116
	// *
	// Comorian Franc
	//
	// * COMOROS (THE)
	//
	CurrencyCode_KMF CurrencyCode = 174
	// *
	// North Korean Won
	//
	// * KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)
	//
	CurrencyCode_KPW CurrencyCode = 408
	// *
	// Won
	//
	// * KOREA (THE REPUBLIC OF)
	//
	CurrencyCode_KRW CurrencyCode = 410
	// *
	// Kuwaiti Dinar
	//
	// * KUWAIT
	//
	CurrencyCode_KWD CurrencyCode = 414
	// *
	// Cayman Islands Dollar
	//
	// * CAYMAN ISLANDS (THE)
	//
	CurrencyCode_KYD CurrencyCode = 136
	// *
	// Tenge
	//
	// * KAZAKHSTAN
	//
	CurrencyCode_KZT CurrencyCode = 398
	// *
	// Lao Kip
	//
	// * LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)
	//
	CurrencyCode_LAK CurrencyCode = 418
	// *
	// Lebanese Pound
	//
	// * LEBANON
	//
	CurrencyCode_LBP CurrencyCode = 422
	// *
	// Sri Lanka Rupee
	//
	// * SRI LANKA
	//
	CurrencyCode_LKR CurrencyCode = 144
	// *
	// Liberian Dollar
	//
	// * LIBERIA
	//
	CurrencyCode_LRD CurrencyCode = 430
	// *
	// Loti
	//
	// * LESOTHO
	//
	CurrencyCode_LSL CurrencyCode = 426
	// *
	// Libyan Dinar
	//
	// * LIBYA
	//
	CurrencyCode_LYD CurrencyCode = 434
	// *
	// Moroccan Dirham
	//
	// * MOROCCO
	// * WESTERN SAHARA
	//
	CurrencyCode_MAD CurrencyCode = 504
	// *
	// Moldovan Leu
	//
	// * MOLDOVA (THE REPUBLIC OF)
	//
	CurrencyCode_MDL CurrencyCode = 498
	// *
	// Malagasy Ariary
	//
	// * MADAGASCAR
	//
	CurrencyCode_MGA CurrencyCode = 969
	// *
	// Denar
	//
	// * MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)
	//
	CurrencyCode_MKD CurrencyCode = 807
	// *
	// Kyat
	//
	// * MYANMAR
	//
	CurrencyCode_MMK CurrencyCode = 104
	// *
	// Tugrik
	//
	// * MONGOLIA
	//
	CurrencyCode_MNT CurrencyCode = 496
	// *
	// Pataca
	//
	// * MACAO
	//
	CurrencyCode_MOP CurrencyCode = 446
	// *
	// Ouguiya
	//
	// * MAURITANIA
	//
	CurrencyCode_MRU CurrencyCode = 929
	// *
	// Mauritius Rupee
	//
	// * MAURITIUS
	//
	CurrencyCode_MUR CurrencyCode = 480
	// *
	// Rufiyaa
	//
	// * MALDIVES
	//
	CurrencyCode_MVR CurrencyCode = 462
	// *
	// Malawi Kwacha
	//
	// * MALAWI
	//
	CurrencyCode_MWK CurrencyCode = 454
	// *
	// Mexican Peso
	//
	// * MEXICO
	//
	CurrencyCode_MXN CurrencyCode = 484
	// *
	// Mexican Unidad de Inversion (UDI)
	//
	// * MEXICO
	//
	CurrencyCode_MXV CurrencyCode = 979
	// *
	// Malaysian Ringgit
	//
	// * MALAYSIA
	//
	CurrencyCode_MYR CurrencyCode = 458
	// *
	// Mozambique Metical
	//
	// * MOZAMBIQUE
	//
	CurrencyCode_MZN CurrencyCode = 943
	// *
	// Namibia Dollar
	//
	// * NAMIBIA
	//
	CurrencyCode_NAD CurrencyCode = 516
	// *
	// Naira
	//
	// * NIGERIA
	//
	CurrencyCode_NGN CurrencyCode = 566
	// *
	// Cordoba Oro
	//
	// * NICARAGUA
	//
	CurrencyCode_NIO CurrencyCode = 558
	// *
	// Norwegian Krone
	//
	// * BOUVET ISLAND
	// * NORWAY
	// * SVALBARD AND JAN MAYEN
	//
	CurrencyCode_NOK CurrencyCode = 578
	// *
	// Nepalese Rupee
	//
	// * NEPAL
	//
	CurrencyCode_NPR CurrencyCode = 524
	// *
	// New Zealand Dollar
	//
	// * COOK ISLANDS (THE)
	// * NEW ZEALAND
	// * NIUE
	// * PITCAIRN
	// * TOKELAU
	//
	CurrencyCode_NZD CurrencyCode = 554
	// *
	// Rial Omani
	//
	// * OMAN
	//
	CurrencyCode_OMR CurrencyCode = 512
	// *
	// Balboa
	//
	// * PANAMA
	//
	CurrencyCode_PAB CurrencyCode = 590
	// *
	// Sol
	//
	// * PERU
	//
	CurrencyCode_PEN CurrencyCode = 604
	// *
	// Kina
	//
	// * PAPUA NEW GUINEA
	//
	CurrencyCode_PGK CurrencyCode = 598
	// *
	// Philippine Piso
	//
	// * PHILIPPINES (THE)
	//
	CurrencyCode_PHP CurrencyCode = 608
	// *
	// Pakistan Rupee
	//
	// * PAKISTAN
	//
	CurrencyCode_PKR CurrencyCode = 586
	// *
	// Zloty
	//
	// * POLAND
	//
	CurrencyCode_PLN CurrencyCode = 985
	// *
	// Guarani
	//
	// * PARAGUAY
	//
	CurrencyCode_PYG CurrencyCode = 600
	// *
	// Qatari Rial
	//
	// * QATAR
	//
	CurrencyCode_QAR CurrencyCode = 634
	// *
	// Romanian Leu
	//
	// * ROMANIA
	//
	CurrencyCode_RON CurrencyCode = 946
	// *
	// Serbian Dinar
	//
	// * SERBIA
	//
	CurrencyCode_RSD CurrencyCode = 941
	// *
	// Russian Ruble
	//
	// * RUSSIAN FEDERATION (THE)
	//
	CurrencyCode_RUB CurrencyCode = 643
	// *
	// Rwanda Franc
	//
	// * RWANDA
	//
	CurrencyCode_RWF CurrencyCode = 646
	// *
	// Saudi Riyal
	//
	// * SAUDI ARABIA
	//
	CurrencyCode_SAR CurrencyCode = 682
	// *
	// Solomon Islands Dollar
	//
	// * SOLOMON ISLANDS
	//
	CurrencyCode_SBD CurrencyCode = 90
	// *
	// Seychelles Rupee
	//
	// * SEYCHELLES
	//
	CurrencyCode_SCR CurrencyCode = 690
	// *
	// Sudanese Pound
	//
	// * SUDAN (THE)
	//
	CurrencyCode_SDG CurrencyCode = 938
	// *
	// Swedish Krona
	//
	// * SWEDEN
	//
	CurrencyCode_SEK CurrencyCode = 752
	// *
	// Singapore Dollar
	//
	// * SINGAPORE
	//
	CurrencyCode_SGD CurrencyCode = 702
	// *
	// Saint Helena Pound
	//
	// * SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA
	//
	CurrencyCode_SHP CurrencyCode = 654
	// *
	// Leone
	//
	// * SIERRA LEONE
	//
	CurrencyCode_SLL CurrencyCode = 694
	// *
	// Somali Shilling
	//
	// * SOMALIA
	//
	CurrencyCode_SOS CurrencyCode = 706
	// *
	// Surinam Dollar
	//
	// * SURINAME
	//
	CurrencyCode_SRD CurrencyCode = 968
	// *
	// South Sudanese Pound
	//
	// * SOUTH SUDAN
	//
	CurrencyCode_SSP CurrencyCode = 728
	// *
	// Dobra
	//
	// * SAO TOME AND PRINCIPE
	//
	CurrencyCode_STN CurrencyCode = 930
	// *
	// El Salvador Colon
	//
	// * EL SALVADOR
	//
	CurrencyCode_SVC CurrencyCode = 222
	// *
	// Syrian Pound
	//
	// * SYRIAN ARAB REPUBLIC
	//
	CurrencyCode_SYP CurrencyCode = 760
	// *
	// Lilangeni
	//
	// * SWAZILAND
	//
	CurrencyCode_SZL CurrencyCode = 748
	// *
	// Baht
	//
	// * THAILAND
	//
	CurrencyCode_THB CurrencyCode = 764
	// *
	// Somoni
	//
	// * TAJIKISTAN
	//
	CurrencyCode_TJS CurrencyCode = 972
	// *
	// Turkmenistan New Manat
	//
	// * TURKMENISTAN
	//
	CurrencyCode_TMT CurrencyCode = 934
	// *
	// Tunisian Dinar
	//
	// * TUNISIA
	//
	CurrencyCode_TND CurrencyCode = 788
	// *
	// Pa’anga
	//
	// * TONGA
	//
	CurrencyCode_TOP CurrencyCode = 776
	// *
	// Turkish Lira
	//
	// * TURKEY
	//
	CurrencyCode_TRY CurrencyCode = 949
	// *
	// Trinidad and Tobago Dollar
	//
	// * TRINIDAD AND TOBAGO
	//
	CurrencyCode_TTD CurrencyCode = 780
	// *
	// New Taiwan Dollar
	//
	// * TAIWAN (PROVINCE OF CHINA)
	//
	CurrencyCode_TWD CurrencyCode = 901
	// *
	// Tanzanian Shilling
	//
	// * TANZANIA, UNITED REPUBLIC OF
	//
	CurrencyCode_TZS CurrencyCode = 834
	// *
	// Hryvnia
	//
	// * UKRAINE
	//
	CurrencyCode_UAH CurrencyCode = 980
	// *
	// Uganda Shilling
	//
	// * UGANDA
	//
	CurrencyCode_UGX CurrencyCode = 800
	// *
	// US Dollar
	//
	// * AMERICAN SAMOA
	// * BONAIRE, SINT EUSTATIUS AND SABA
	// * BRITISH INDIAN OCEAN TERRITORY (THE)
	// * ECUADOR
	// * EL SALVADOR
	// * GUAM
	// * HAITI
	// * MARSHALL ISLANDS (THE)
	// * MICRONESIA (FEDERATED STATES OF)
	// * NORTHERN MARIANA ISLANDS (THE)
	// * PALAU
	// * PANAMA
	// * PUERTO RICO
	// * TIMOR-LESTE
	// * TURKS AND CAICOS ISLANDS (THE)
	// * UNITED STATES MINOR OUTLYING ISLANDS (THE)
	// * UNITED STATES OF AMERICA (THE)
	// * VIRGIN ISLANDS (BRITISH)
	// * VIRGIN ISLANDS (U.S.)
	//
	CurrencyCode_USD CurrencyCode = 840
	// *
	// US Dollar (Next day)
	//
	// * UNITED STATES OF AMERICA (THE)
	//
	CurrencyCode_USN CurrencyCode = 997
	// *
	// Uruguay Peso en Unidades Indexadas (URUIURUI)
	//
	// * URUGUAY
	//
	CurrencyCode_UYI CurrencyCode = 940
	// *
	// Peso Uruguayo
	//
	// * URUGUAY
	//
	CurrencyCode_UYU CurrencyCode = 858
	// *
	// Uzbekistan Sum
	//
	// * UZBEKISTAN
	//
	CurrencyCode_UZS CurrencyCode = 860
	// *
	// Bolívar
	//
	// * VENEZUELA (BOLIVARIAN REPUBLIC OF)
	//
	CurrencyCode_VEF CurrencyCode = 937
	// *
	// Dong
	//
	// * VIET NAM
	//
	CurrencyCode_VND CurrencyCode = 704
	// *
	// Vatu
	//
	// * VANUATU
	//
	CurrencyCode_VUV CurrencyCode = 548
	// *
	// Tala
	//
	// * SAMOA
	//
	CurrencyCode_WST CurrencyCode = 882
	// *
	// CFA Franc BEAC
	//
	// * CAMEROON
	// * CENTRAL AFRICAN REPUBLIC (THE)
	// * CHAD
	// * CONGO (THE)
	// * EQUATORIAL GUINEA
	// * GABON
	//
	CurrencyCode_XAF CurrencyCode = 950
	// *
	// Silver
	//
	// * ZZ11_Silver
	//
	CurrencyCode_XAG CurrencyCode = 961
	// *
	// Gold
	//
	// * ZZ08_Gold
	//
	CurrencyCode_XAU CurrencyCode = 959
	// *
	// Bond Markets Unit European Composite Unit (EURCO)
	//
	// * ZZ01_Bond Markets Unit European_EURCO
	//
	CurrencyCode_XBA CurrencyCode = 955
	// *
	// Bond Markets Unit European Monetary Unit (E.M.U.-6)
	//
	// * ZZ02_Bond Markets Unit European_EMU-6
	//
	CurrencyCode_XBB CurrencyCode = 956
	// *
	// Bond Markets Unit European Unit of Account 9 (E.U.A.-9)
	//
	// * ZZ03_Bond Markets Unit European_EUA-9
	//
	CurrencyCode_XBC CurrencyCode = 957
	// *
	// Bond Markets Unit European Unit of Account 17 (E.U.A.-17)
	//
	// * ZZ04_Bond Markets Unit European_EUA-17
	//
	CurrencyCode_XBD CurrencyCode = 958
	// *
	// East Caribbean Dollar
	//
	// * ANGUILLA
	// * ANTIGUA AND BARBUDA
	// * DOMINICA
	// * GRENADA
	// * MONTSERRAT
	// * SAINT KITTS AND NEVIS
	// * SAINT LUCIA
	// * SAINT VINCENT AND THE GRENADINES
	//
	CurrencyCode_XCD CurrencyCode = 951
	// *
	// SDR (Special Drawing Right)
	//
	// * INTERNATIONAL MONETARY FUND (IMF)
	//
	CurrencyCode_XDR CurrencyCode = 960
	// *
	// CFA Franc BCEAO
	//
	// * BENIN
	// * BURKINA FASO
	// * CÔTE D'IVOIRE
	// * GUINEA-BISSAU
	// * MALI
	// * NIGER (THE)
	// * SENEGAL
	// * TOGO
	//
	CurrencyCode_XOF CurrencyCode = 952
	// *
	// Palladium
	//
	// * ZZ09_Palladium
	//
	CurrencyCode_XPD CurrencyCode = 964
	// *
	// CFP Franc
	//
	// * FRENCH POLYNESIA
	// * NEW CALEDONIA
	// * WALLIS AND FUTUNA
	//
	CurrencyCode_XPF CurrencyCode = 953
	// *
	// Platinum
	//
	// * ZZ10_Platinum
	//
	CurrencyCode_XPT CurrencyCode = 962
	// *
	// Sucre
	//
	// * SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"
	//
	CurrencyCode_XSU CurrencyCode = 994
	// *
	// Codes specifically reserved for testing purposes
	//
	// * ZZ06_Testing_Code
	//
	CurrencyCode_XTS CurrencyCode = 963
	// *
	// ADB Unit of Account
	//
	// * MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP
	//
	CurrencyCode_XUA CurrencyCode = 965
	// *
	// The codes assigned for transactions where no currency is involved
	//
	// * ZZ07_No_Currency
	//
	CurrencyCode_XXX CurrencyCode = 999
	// *
	// Yemeni Rial
	//
	// * YEMEN
	//
	CurrencyCode_YER CurrencyCode = 886
	// *
	// Rand
	//
	// * LESOTHO
	// * NAMIBIA
	// * SOUTH AFRICA
	//
	CurrencyCode_ZAR CurrencyCode = 710
	// *
	// Zambian Kwacha
	//
	// * ZAMBIA
	//
	CurrencyCode_ZMW CurrencyCode = 967
	// *
	// Zimbabwe Dollar
	//
	// * ZIMBABWE
	//
	CurrencyCode_ZWL CurrencyCode = 932
)

var CurrencyCode_name = map[int32]string{
	0:   "_",
	784: "AED",
	971: "AFN",
	8:   "ALL",
	51:  "AMD",
	532: "ANG",
	973: "AOA",
	32:  "ARS",
	36:  "AUD",
	533: "AWG",
	944: "AZN",
	977: "BAM",
	52:  "BBD",
	50:  "BDT",
	975: "BGN",
	48:  "BHD",
	108: "BIF",
	60:  "BMD",
	96:  "BND",
	68:  "BOB",
	984: "BOV",
	986: "BRL",
	44:  "BSD",
	64:  "BTN",
	72:  "BWP",
	933: "BYN",
	84:  "BZD",
	124: "CAD",
	976: "CDF",
	947: "CHE",
	756: "CHF",
	948: "CHW",
	990: "CLF",
	152: "CLP",
	156: "CNY",
	170: "COP",
	970: "COU",
	188: "CRC",
	931: "CUC",
	192: "CUP",
	132: "CVE",
	203: "CZK",
	262: "DJF",
	208: "DKK",
	214: "DOP",
	12:  "DZD",
	818: "EGP",
	232: "ERN",
	230: "ETB",
	978: "EUR",
	242: "FJD",
	238: "FKP",
	826: "GBP",
	981: "GEL",
	936: "GHS",
	292: "GIP",
	270: "GMD",
	324: "GNF",
	320: "GTQ",
	328: "GYD",
	344: "HKD",
	340: "HNL",
	191: "HRK",
	332: "HTG",
	348: "HUF",
	360: "IDR",
	376: "ILS",
	356: "INR",
	368: "IQD",
	364: "IRR",
	352: "ISK",
	388: "JMD",
	400: "JOD",
	392: "JPY",
	404: "KES",
	417: "KGS",
	116: "KHR",
	174: "KMF",
	408: "KPW",
	410: "KRW",
	414: "KWD",
	136: "KYD",
	398: "KZT",
	418: "LAK",
	422: "LBP",
	144: "LKR",
	430: "LRD",
	426: "LSL",
	434: "LYD",
	504: "MAD",
	498: "MDL",
	969: "MGA",
	807: "MKD",
	104: "MMK",
	496: "MNT",
	446: "MOP",
	929: "MRU",
	480: "MUR",
	462: "MVR",
	454: "MWK",
	484: "MXN",
	979: "MXV",
	458: "MYR",
	943: "MZN",
	516: "NAD",
	566: "NGN",
	558: "NIO",
	578: "NOK",
	524: "NPR",
	554: "NZD",
	512: "OMR",
	590: "PAB",
	604: "PEN",
	598: "PGK",
	608: "PHP",
	586: "PKR",
	985: "PLN",
	600: "PYG",
	634: "QAR",
	946: "RON",
	941: "RSD",
	643: "RUB",
	646: "RWF",
	682: "SAR",
	90:  "SBD",
	690: "SCR",
	938: "SDG",
	752: "SEK",
	702: "SGD",
	654: "SHP",
	694: "SLL",
	706: "SOS",
	968: "SRD",
	728: "SSP",
	930: "STN",
	222: "SVC",
	760: "SYP",
	748: "SZL",
	764: "THB",
	972: "TJS",
	934: "TMT",
	788: "TND",
	776: "TOP",
	949: "TRY",
	780: "TTD",
	901: "TWD",
	834: "TZS",
	980: "UAH",
	800: "UGX",
	840: "USD",
	997: "USN",
	940: "UYI",
	858: "UYU",
	860: "UZS",
	937: "VEF",
	704: "VND",
	548: "VUV",
	882: "WST",
	950: "XAF",
	961: "XAG",
	959: "XAU",
	955: "XBA",
	956: "XBB",
	957: "XBC",
	958: "XBD",
	951: "XCD",
	960: "XDR",
	952: "XOF",
	964: "XPD",
	953: "XPF",
	962: "XPT",
	994: "XSU",
	963: "XTS",
	965: "XUA",
	999: "XXX",
	886: "YER",
	710: "ZAR",
	967: "ZMW",
	932: "ZWL",
}
var CurrencyCode_value = map[string]int32{
	"_":   0,
	"AED": 784,
	"AFN": 971,
	"ALL": 8,
	"AMD": 51,
	"ANG": 532,
	"AOA": 973,
	"ARS": 32,
	"AUD": 36,
	"AWG": 533,
	"AZN": 944,
	"BAM": 977,
	"BBD": 52,
	"BDT": 50,
	"BGN": 975,
	"BHD": 48,
	"BIF": 108,
	"BMD": 60,
	"BND": 96,
	"BOB": 68,
	"BOV": 984,
	"BRL": 986,
	"BSD": 44,
	"BTN": 64,
	"BWP": 72,
	"BYN": 933,
	"BZD": 84,
	"CAD": 124,
	"CDF": 976,
	"CHE": 947,
	"CHF": 756,
	"CHW": 948,
	"CLF": 990,
	"CLP": 152,
	"CNY": 156,
	"COP": 170,
	"COU": 970,
	"CRC": 188,
	"CUC": 931,
	"CUP": 192,
	"CVE": 132,
	"CZK": 203,
	"DJF": 262,
	"DKK": 208,
	"DOP": 214,
	"DZD": 12,
	"EGP": 818,
	"ERN": 232,
	"ETB": 230,
	"EUR": 978,
	"FJD": 242,
	"FKP": 238,
	"GBP": 826,
	"GEL": 981,
	"GHS": 936,
	"GIP": 292,
	"GMD": 270,
	"GNF": 324,
	"GTQ": 320,
	"GYD": 328,
	"HKD": 344,
	"HNL": 340,
	"HRK": 191,
	"HTG": 332,
	"HUF": 348,
	"IDR": 360,
	"ILS": 376,
	"INR": 356,
	"IQD": 368,
	"IRR": 364,
	"ISK": 352,
	"JMD": 388,
	"JOD": 400,
	"JPY": 392,
	"KES": 404,
	"KGS": 417,
	"KHR": 116,
	"KMF": 174,
	"KPW": 408,
	"KRW": 410,
	"KWD": 414,
	"KYD": 136,
	"KZT": 398,
	"LAK": 418,
	"LBP": 422,
	"LKR": 144,
	"LRD": 430,
	"LSL": 426,
	"LYD": 434,
	"MAD": 504,
	"MDL": 498,
	"MGA": 969,
	"MKD": 807,
	"MMK": 104,
	"MNT": 496,
	"MOP": 446,
	"MRU": 929,
	"MUR": 480,
	"MVR": 462,
	"MWK": 454,
	"MXN": 484,
	"MXV": 979,
	"MYR": 458,
	"MZN": 943,
	"NAD": 516,
	"NGN": 566,
	"NIO": 558,
	"NOK": 578,
	"NPR": 524,
	"NZD": 554,
	"OMR": 512,
	"PAB": 590,
	"PEN": 604,
	"PGK": 598,
	"PHP": 608,
	"PKR": 586,
	"PLN": 985,
	"PYG": 600,
	"QAR": 634,
	"RON": 946,
	"RSD": 941,
	"RUB": 643,
	"RWF": 646,
	"SAR": 682,
	"SBD": 90,
	"SCR": 690,
	"SDG": 938,
	"SEK": 752,
	"SGD": 702,
	"SHP": 654,
	"SLL": 694,
	"SOS": 706,
	"SRD": 968,
	"SSP": 728,
	"STN": 930,
	"SVC": 222,
	"SYP": 760,
	"SZL": 748,
	"THB": 764,
	"TJS": 972,
	"TMT": 934,
	"TND": 788,
	"TOP": 776,
	"TRY": 949,
	"TTD": 780,
	"TWD": 901,
	"TZS": 834,
	"UAH": 980,
	"UGX": 800,
	"USD": 840,
	"USN": 997,
	"UYI": 940,
	"UYU": 858,
	"UZS": 860,
	"VEF": 937,
	"VND": 704,
	"VUV": 548,
	"WST": 882,
	"XAF": 950,
	"XAG": 961,
	"XAU": 959,
	"XBA": 955,
	"XBB": 956,
	"XBC": 957,
	"XBD": 958,
	"XCD": 951,
	"XDR": 960,
	"XOF": 952,
	"XPD": 964,
	"XPF": 953,
	"XPT": 962,
	"XSU": 994,
	"XTS": 963,
	"XUA": 965,
	"XXX": 999,
	"YER": 886,
	"ZAR": 710,
	"ZMW": 967,
	"ZWL": 932,
}

func (x CurrencyCode) String() string {
	return proto.EnumName(CurrencyCode_name, int32(x))
}
func (CurrencyCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("currency.CurrencyCode", CurrencyCode_name, CurrencyCode_value)
}

func init() { proto.RegisterFile("4217.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 949 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xd5, 0xcd, 0x6b, 0x1d, 0x65,
	0x14, 0x06, 0x70, 0x6b, 0xcc, 0x07, 0x97, 0x0a, 0x0f, 0xf9, 0x0b, 0x5c, 0xb8, 0x12, 0x11, 0x6d,
	0x0b, 0x6e, 0x5c, 0x38, 0x73, 0xcf, 0xcc, 0xdc, 0x64, 0x66, 0xde, 0x99, 0xbc, 0x33, 0x73, 0x27,
	0x33, 0x1b, 0xc5, 0x5a, 0x70, 0x21, 0x46, 0x42, 0x5d, 0x08, 0x2e, 0x04, 0x63, 0xc9, 0xa2, 0x84,
	0x2c, 0x22, 0x14, 0x11, 0xb1, 0x35, 0x56, 0x0d, 0x1a, 0x25, 0x6a, 0xfc, 0xaa, 0x69, 0x8c, 0xb5,
	0xc6, 0xb4, 0xd6, 0xaa, 0xb5, 0xc4, 0x12, 0x4a, 0x90, 0xaa, 0x5d, 0x14, 0x09, 0x41, 0x25, 0x88,
	0x0b, 0xb9, 0xe7, 0x99, 0xdd, 0x2f, 0xcf, 0x39, 0x67, 0xe6, 0xe4, 0x1d, 0x5e, 0x6e, 0xab, 0x75,
	0xe8, 0xc0, 0x03, 0x0f, 0xde, 0xf7, 0xf4, 0xe4, 0xc4, 0xd1, 0x89, 0xe1, 0xa1, 0xc3, 0xcf, 0x4c,
	0x4e, 0x1e, 0x79, 0xea, 0xf0, 0xb3, 0xf7, 0xfc, 0x7d, 0x67, 0x6b, 0x7f, 0xbb, 0xf9, 0xa3, 0x3d,
	0xf1, 0xf8, 0x91, 0xe1, 0xfe, 0xd6, 0xbe, 0x47, 0x70, 0xdb, 0xf0, 0x50, 0xab, 0xcf, 0xf1, 0x04,
	0xb3, 0x03, 0x2a, 0xdf, 0xe0, 0xc2, 0xe0, 0xf0, 0x60, 0xab, 0xcf, 0x89, 0x22, 0x0c, 0x29, 0x62,
	0xc1, 0x41, 0xad, 0x99, 0x00, 0x73, 0x77, 0xa8, 0x12, 0x07, 0xdf, 0xb1, 0xcb, 0x66, 0xb8, 0x4b,
	0x51, 0x08, 0xee, 0xd6, 0x5a, 0x19, 0xe0, 0x25, 0x76, 0xd5, 0x06, 0xef, 0x0f, 0xf6, 0xe4, 0x3a,
	0x31, 0x7e, 0xd0, 0x7e, 0xd7, 0x15, 0x1c, 0x52, 0x48, 0x8e, 0x03, 0x5a, 0x0b, 0x0c, 0xbe, 0x67,
	0xad, 0x23, 0xb8, 0x5f, 0x31, 0xe2, 0xe3, 0x49, 0x45, 0x2c, 0x78, 0x48, 0x61, 0x04, 0x8f, 0x2a,
	0x12, 0x17, 0xa2, 0x63, 0x49, 0x17, 0x9b, 0x7c, 0xb8, 0x8d, 0x70, 0x8d, 0x0f, 0xc8, 0x04, 0xf7,
	0x2a, 0x72, 0x83, 0x87, 0x15, 0x65, 0x8a, 0x8e, 0x36, 0x55, 0x06, 0x6f, 0xb0, 0xa9, 0x16, 0xe4,
	0x3d, 0xb4, 0x1d, 0xc1, 0x73, 0xbd, 0x5a, 0x5b, 0x7c, 0x5c, 0xd6, 0x47, 0xb5, 0x3b, 0x1e, 0x3e,
	0x68, 0xe4, 0xe3, 0xaf, 0x7e, 0xaa, 0xc4, 0x87, 0xcc, 0x22, 0x1f, 0xd7, 0x1b, 0xa5, 0x38, 0xb1,
	0x4f, 0x65, 0x2a, 0xbc, 0x42, 0x25, 0x29, 0x16, 0x1a, 0x15, 0xd8, 0x60, 0x9f, 0x6d, 0xe3, 0x0c,
	0xb3, 0xa2, 0x8d, 0xd7, 0x99, 0x15, 0x29, 0x56, 0x99, 0x75, 0x3d, 0x4c, 0x51, 0x75, 0x88, 0x0b,
	0x2a, 0x19, 0xf5, 0x71, 0xec, 0x76, 0x55, 0x18, 0xe2, 0x32, 0xb3, 0x24, 0xc5, 0xd5, 0x7d, 0xbd,
	0x95, 0xa5, 0x16, 0xec, 0xef, 0x45, 0x5e, 0x90, 0x62, 0x49, 0x3f, 0x98, 0x67, 0x0d, 0x6e, 0x6a,
	0x9b, 0x97, 0xbb, 0xf8, 0x9d, 0x2a, 0x2c, 0x7e, 0xd4, 0x97, 0xf9, 0xa3, 0x82, 0x5d, 0xcd, 0xfc,
	0x30, 0xc5, 0x9f, 0xaa, 0xc0, 0x4d, 0xf1, 0x99, 0xce, 0x06, 0x5e, 0x84, 0x9f, 0xb5, 0x2f, 0xe8,
	0x64, 0x78, 0x8b, 0x1a, 0x49, 0x31, 0xaf, 0x0b, 0x04, 0xb1, 0x60, 0x86, 0x32, 0x3e, 0xce, 0x51,
	0xf9, 0x18, 0x56, 0xa9, 0x4a, 0xb0, 0xae, 0xea, 0x84, 0x82, 0x4d, 0xca, 0x44, 0xb8, 0x42, 0xd9,
	0x10, 0x67, 0xf5, 0x6d, 0x9d, 0x3c, 0xc0, 0x45, 0x66, 0x85, 0x8f, 0x2d, 0xd5, 0x88, 0x58, 0xdc,
	0xa4, 0xa2, 0x0c, 0x7b, 0x94, 0xb1, 0xb8, 0x41, 0x8d, 0x09, 0x76, 0x28, 0x6b, 0x71, 0x8b, 0xca,
	0x42, 0x6c, 0xab, 0x46, 0x63, 0xc1, 0x54, 0x9f, 0x2a, 0x11, 0xcc, 0x52, 0x69, 0x85, 0x69, 0x55,
	0xe8, 0x65, 0x98, 0xa3, 0x82, 0x0c, 0x27, 0xfb, 0x7a, 0x87, 0x16, 0x76, 0x2c, 0x8e, 0x6a, 0x14,
	0xfb, 0x58, 0xd4, 0xa5, 0xc2, 0xb4, 0xc4, 0x09, 0xb6, 0xd9, 0x12, 0x2f, 0x53, 0xa5, 0xe0, 0x55,
	0xaa, 0x12, 0x4c, 0xb3, 0xaf, 0xce, 0x31, 0xa3, 0x59, 0xe4, 0x84, 0x38, 0x45, 0xb9, 0x29, 0x4e,
	0x53, 0xa1, 0xc5, 0xac, 0xf6, 0x45, 0x56, 0xb0, 0xc8, 0x2c, 0x8b, 0xb0, 0x40, 0x55, 0x82, 0x25,
	0x55, 0xec, 0x08, 0xf6, 0x28, 0x89, 0xb0, 0x4b, 0x05, 0x0e, 0xbe, 0xd5, 0x03, 0x8f, 0x43, 0xc1,
	0x9b, 0x03, 0xbd, 0x45, 0xe3, 0x38, 0xc4, 0x13, 0x1a, 0x99, 0x1c, 0x3b, 0x6c, 0x4b, 0x52, 0xac,
	0x50, 0xb6, 0xc0, 0x49, 0x0e, 0x14, 0x16, 0xdb, 0xcc, 0xba, 0x16, 0x97, 0xa8, 0x32, 0xc4, 0x79,
	0x6a, 0xdc, 0xe0, 0x46, 0xa3, 0x2e, 0x7e, 0xe2, 0x44, 0x65, 0xb1, 0xc1, 0xac, 0x36, 0x78, 0x4f,
	0x33, 0xe3, 0x08, 0xa6, 0xf4, 0x9a, 0x9a, 0xc0, 0x60, 0x99, 0x1a, 0x49, 0xb0, 0x48, 0x25, 0x21,
	0xd6, 0xa8, 0xd4, 0xe2, 0x38, 0x55, 0x0b, 0x16, 0x54, 0x49, 0x6c, 0xf1, 0xbc, 0x2a, 0x75, 0x5c,
	0x5c, 0xa2, 0x3c, 0x83, 0x2d, 0x2a, 0x08, 0x71, 0x95, 0xea, 0xa4, 0xd8, 0xa6, 0x42, 0x8b, 0x0d,
	0x2a, 0x32, 0xf8, 0x45, 0x37, 0x48, 0xab, 0x00, 0x9b, 0x9a, 0x8d, 0x39, 0x16, 0xff, 0xaa, 0x6c,
	0x62, 0xb0, 0xa4, 0x55, 0x9b, 0x09, 0xde, 0xa5, 0x0a, 0x17, 0x2f, 0xe8, 0x55, 0xb4, 0xa5, 0x8f,
	0x63, 0xaa, 0xcc, 0xb1, 0x58, 0xe8, 0xef, 0x1d, 0x5a, 0xe6, 0x0a, 0x6a, 0x8d, 0xda, 0x16, 0x4b,
	0x2c, 0x4a, 0x80, 0x05, 0x1d, 0xcd, 0xbc, 0x10, 0x3b, 0xcc, 0x02, 0xc1, 0x0a, 0xd5, 0x49, 0x31,
	0x43, 0x45, 0x11, 0x96, 0xa9, 0x24, 0xc3, 0x1a, 0x65, 0x05, 0xeb, 0x9c, 0xcd, 0x52, 0x6c, 0x32,
	0xcb, 0x0d, 0x4e, 0x31, 0xeb, 0xb6, 0x71, 0x5d, 0xbf, 0x78, 0x56, 0xa5, 0xd8, 0x63, 0xb5, 0x8e,
	0x70, 0x4b, 0x95, 0x77, 0x5c, 0xfc, 0x47, 0x8d, 0x66, 0xb8, 0xa8, 0x13, 0x79, 0x9c, 0xe3, 0x34,
	0x65, 0x04, 0x73, 0x7a, 0xed, 0xf2, 0x24, 0xc5, 0x34, 0x65, 0x2b, 0x7c, 0xc4, 0x6a, 0x2e, 0x38,
	0xce, 0xac, 0x14, 0xbc, 0xc8, 0xac, 0xce, 0xb0, 0xa6, 0x59, 0xe1, 0x74, 0x70, 0x45, 0xb3, 0x22,
	0x18, 0xc7, 0x6b, 0xcc, 0x32, 0xc1, 0x7a, 0x23, 0x83, 0xdf, 0x58, 0xad, 0x46, 0xf0, 0x4e, 0xa3,
	0x02, 0xd7, 0x58, 0xad, 0x33, 0x6c, 0xa9, 0xba, 0x9e, 0x8f, 0xb7, 0xb5, 0xda, 0x35, 0x82, 0x55,
	0xdd, 0xb4, 0x5b, 0x74, 0x31, 0xaf, 0x47, 0x5f, 0x66, 0x39, 0x76, 0xb5, 0x6f, 0xdc, 0xf1, 0xb1,
	0x3c, 0x48, 0x05, 0xf8, 0xb2, 0x51, 0x81, 0xb3, 0x94, 0xeb, 0xe0, 0xf3, 0x46, 0x2e, 0xce, 0x34,
	0x6a, 0xe3, 0x8b, 0x46, 0x82, 0x15, 0xaa, 0x2d, 0xf8, 0x98, 0x12, 0x8b, 0x55, 0x2a, 0xf1, 0xf1,
	0x09, 0x95, 0x0a, 0xce, 0x35, 0xf2, 0xf1, 0x69, 0xa3, 0x1c, 0x6b, 0x54, 0x56, 0xe0, 0x57, 0x2a,
	0xcf, 0xf0, 0x15, 0x55, 0x38, 0xf8, 0x9a, 0x1a, 0x1f, 0xc7, 0x1f, 0xaa, 0xca, 0xb3, 0xf8, 0x47,
	0x77, 0xae, 0x1d, 0x8b, 0xf3, 0xfa, 0x1f, 0xd5, 0x71, 0x89, 0x6f, 0xb4, 0x5a, 0x97, 0x11, 0xe6,
	0x07, 0x1f, 0x1b, 0xd0, 0x1f, 0xc2, 0x83, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x08, 0xa2,
	0x1d, 0x16, 0x07, 0x00, 0x00,
}
